version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=prisma
    networks:
      - next-auth-net
    volumes:
      - next-auth-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    # restart: always
    ports:
      - 3000:3000
    env_file: .env
    command:  sh -c 'npx prisma db push --preview-feature && npm run dev'
    depends_on:
      - postgres
    networks:
      - next-auth-net
    volumes:
      - ./pages:/usr/src/app/pages
      - ./@:/app/@
      - ./public:/usr/src/app.public

volumes:
  next-auth-data:
networks:
  next-auth-net:
